# Do not read upstream DNS servers from /etc/resolv.conf
no-resolv

# Forward all queries to unbound inside docker
server=172.28.0.7#5335

# Listen on all interfaces inside the container
# (port binding on host controls exposure)
listen-address=0.0.0.0
bind-interfaces

# Cache
cache-size=10000
min-cache-ttl=3600
max-cache-ttl=86400

# Always use static entries from /etc/hosts
addn-hosts=/etc/hosts

# Logging
log-queries
log-facility=/var/log/dnsmasq.log