services:
  sing-box:
#    image: ghcr.io/sagernet/sing-box:latest
    image: docker.behnam.pro/sagernet/sing-box:war
    container_name: sing-box
    restart: unless-stopped
    expose:
      - "7890"
    volumes:
      - ./sing-box/config.json:/etc/sing-box/config.json
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    networks:
      dns_net:
        ipv4_address: 172.28.0.4


  dnscrypt:
#    image: gists/dnscrypt-proxy
    image: docker.behnam.pro/gists/dnscrypt-proxy:war
    container_name: dnscrypt
    restart: unless-stopped
    expose:
      - "53"
    volumes:
      - ./dnscrypt/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml
      - ./dnscrypt/forwarding-rules.txt:/etc/dnscrypt-proxy/forwarding-rules.txt
      - ./dnscrypt/cloaking-rules.txt:/etc/dnscrypt-proxy/cloaking-rules.txt
      - ./dnscrypt/public-resolvers.md:/var/cache/dnscrypt-proxy/public-resolvers.md
    depends_on:
      - sing-box
    networks:
      dns_net:
        ipv4_address: 172.28.0.3

  dnsdist:
#    image: powerdns/dnsdist-19:1.9.11
    image: docker.behnam.pro/powerdns/dnsdist-19:war
    container_name: dnsdist
    restart: unless-stopped
    environment:
      DNSDIST_STALE_CACHE_ENABLED: "true"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8083:8083/tcp"
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
      - ./dnsdist/ir-domains.txt:/etc/dnsdist/ir-domains.txt:ro
      - ./dnsdist/free-domains.txt:/etc/dnsdist/free-domains.txt:ro
      - ./dnsdist/hosts:/etc/dnsdist/hosts.override:ro
    depends_on:
      - dnscrypt
    networks:
      dns_net:
        ipv4_address: 172.28.0.6

networks:
  dns_net:
    name: dns_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/28
