server:
    interface: 0.0.0.0
    port: 5335
    access-control: 127.0.0.0/8 allow
    access-control: 172.28.0.0/28 allow

    # Allow using localhost as a forwarder (dnsdist)
    do-not-query-localhost: no

    # Disable DNSSEC validation completely in national mode
    module-config: "iterator"

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    edns-buffer-size: 1232

    msg-cache-size: 256m
    rrset-cache-size: 512m

    # serve-expired: yes
    # serve-expired-ttl: 86400
    # serve-expired-reply-ttl: 60

    verbosity: 1


# Keep answers cached for 30 days even if authoritative TTL is smaller
    cache-min-ttl: 2592000
    cache-max-ttl: 2592000

    # Serve stale data when upstream is unreachable
    serve-expired: yes
    serve-expired-ttl: 2592000
    serve-expired-reply-ttl: 60

    # Refresh popular records proactively (recommended for unstable links)
    prefetch: yes
    prefetch-key: yes

    # Optional: avoid keeping NXDOMAIN too long
    cache-max-negative-ttl: 300

forward-zone:
    name: "."
    forward-addr: 172.28.0.6@5353